### ISSUE TITLE
Incompatibility with AMD GPUs

### ISSUE THREAD

**Issue by angeerey** [Meldexun/Nothirium#1]
**Describe the bug**
Massive visual bug, the entire world is invisible other than a wall of colors. See the picture below.

**To Reproduce**
1. Go to any new or existing world
2. Select the world and play
3. Bug is produced

**Screenshots/Videos**
![2022-05-22_09 40 49](https://user-images.githubusercontent.com/64048370/169698469-68c0817c-4aaf-4b53-82c5-167d6ac28372.png)

![2022-05-22_09 48 19](https://user-images.githubusercontent.com/64048370/169699141-f8ece549-703f-42b6-b7ba-988426446ddc.png)

**Versions**
Nothirium: 1.12.2-0.1.0-beta
RenderLib: 1.12.2-1.0.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods: No other mods installed

(P.S, forced threaded chunk rendering was turned off)

**Log File**
[https://pastebin.com/S8rg5ybh](https://pastebin.com/S8rg5ybh)

**Comment by Meldexun** [comment]
Someone else reported the same issue. It looks like this is an issue with AMD GPUs only.
