### ISSUE TITLE
GregTech Crash

### ISSUE THREAD

**Issue by S1mpleM0use** [Meldexun/Nothirium#11]
Crash happens when joining a world with Nothirium and GTCEu installed. Log file is attached below. Blames GTCEu's bloom for some reason, but I have every single shader and bloom effect turned off in the config of GT.

1. Install GregTech CE: Unofficial (https://www.curseforge.com/minecraft/mc-mods/gregtech-ce-unofficial)
2. Install Nothirium
3. Create a new world
4. Get a crash

**Versions**
Nothirium: 0.1.3 beta
RenderLib: 1.0.6
Forge: 2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): gregtech-1.12.2-2.3.0-beta.jar

**Hardware**
CPU: i7 8700k
RAM: 16gb
GPU: NVidia RTX 2080
VRAM: 8gb

**Log file**
https://gist.github.com/S1mpleM0use/e9c5bee18263ac779c480225e266009a

[crash-2022-05-27_15.25.19-client.txt](https://github.com/Meldexun/Nothirium/files/8786644/crash-2022-05-27_15.25.19-client.txt)

**Comment by SlimeX300alt** [comment]
Did you read the description of the nothirium mod properly on curseforge? Currently nothirium is incompatible with gregtech CE: unofficial.

**Comment by S1mpleM0use** [comment]
> Did you read the description of the nothirium mod properly on curseforge? Currently nothirium is incompatible with gregtech CE: unofficial.

It appeared on the page because of this bug-report :)

**Comment by SlimeX300alt** [comment]
> > Did you read the description of the nothirium mod properly on curseforge? Currently nothirium is incompatible with gregtech CE: unofficial.
> 
> It appeared on the page because of this bug-report :)

oh ok :)
