### ISSUE TITLE
Phosphor

### ISSUE THREAD

**Issue by xingchengs** [Meldexun/Nothirium#12]
Will there be incompatibility with phosphor? When I test, the two mods are installed together, and the blocks are all transparent, but the client does not crash

**Comment by Meldexun** [comment]
It works fine for me.
Please use the issue template when reporting bugs as I can't do anything to help you now.

**Comment by xingchengs** [comment]
Not mixinbooter?



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 7, 2022 20:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Meldexun/Nothirium] Phosphor (Issue #12)




 
@xingchengs do you have [MixinCompat-0.8] mod installed?

**Comment by quentin452** [comment]
use [MixinCompat-0.8] normally he will fix the crash

**Comment by xingchengs** [comment]
I will have time to test later. I am very busy recently. I will send the crash log when I test!



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 7, 2022 21:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Meldexun/Nothirium] Phosphor (Issue #12)




 
if its still crash send the logs

**Comment by xingchengs** [comment]
---Original---
From: ***@***.***&gt;
Date: Tue, Jun 7, 2022 21:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Meldexun/Nothirium] Phosphor (Issue #12)




 
if its still crash send the logs
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
 
              
                                        从QQ邮箱发来的超大附件                      
                                                                                        
                               Desktop.rar (114.72K, 无限期)                                                       进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=cdc969631e18d894ffba1b6363626239d2fc34636162623917195057545757585100185204515a14060300534c03000c0a1b53540753550f570351555153693976534608150d121740574777e0fea4a01b37c0c18b456ad356d0a50b9ea19752&t=exs_ftn_download&code=265cabb9

**Comment by quentin452** [comment]
add this mod
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

Le ven. 10 juin 2022 à 08:19, xingchengs ***@***.***> a
écrit :

**Comment by quentin452** [comment]
me when i use gregtech and nothirium , crash maybe just nothirium the
problem

**Comment by Meldexun** [comment]
Closing this now because the author doesn't provide the information requested in the issue template.
