### ISSUE TITLE
Black graphic glitch (whitout smooth lighting)

### ISSUE THREAD

**Issue by quentin452** [Meldexun/Nothirium#15]
**Describe the bug**

I have black graphic issue when i place oak stair and certain other block

**To Reproduce**

1. disable smooth lighting
2. Make new world
3. Place a oak stair
4. See graphic glitch

**Screenshots/Videos**

https://i.imgur.com/8ttZiUo.png
https://i.imgur.com/H0VeNXo.png

**Versions**

Nothirium: Nothirium-1.12.2-0.1.4-beta
RenderLib: RenderLib-1.12.2-1.0.7
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
[___MixinCompat-0.8___],
 _MixinBootstrap-1.1.0

**Hardware**

PC: laptop
CPU: Intel Celeron N4120 CPU @ 1.10GHz
RAM: 4GB Ram (3,4 ram usable)(i don't know if the ram is in ddr4)
GPU: Intel UHD Graphics 600
VRAM: 128Mb

**Log File**
[latest.log](https://github.com/Meldexun/Nothirium/files/8806316/latest.log)

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.1.5-beta
