### ISSUE TITLE
ERROR OPENGL 1282

### ISSUE THREAD

**Issue by quentin452** [Meldexun/Nothirium#17]
**Describe the bug**

When i load world with my intel uhd graphic 600 card , i have error opengl 1282 in logs

**To Reproduce**

1. Make a world
2. Watch in logs GL ERROR

**Screenshots/Videos**

https://i.imgur.com/JKGWiCq.png

Versions

Nothirium: Nothirium-1.12.2-0.1.4-beta
RenderLib: RenderLib-1.12.2-1.0.7
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
[MixinCompat-0.8],
_MixinBootstrap-1.1.0

Hardware

PC: laptop
CPU: Intel Celeron N4120 CPU @ 1.10GHz
RAM: 4GB Ram (3,4 ram usable)(i don't know if the ram is in ddr4)
GPU: Intel UHD Graphics 600
VRAM: 128Mb

**Log File**

[latest.log](https://github.com/Meldexun/Nothirium/files/8813404/latest.log)

**Comment by quentin452** [comment]
because of this error my fps is halved, so I removed the mod temporarily

**Comment by Meldexun** [comment]
[gltest.zip](https://github.com/Meldexun/Nothirium/files/8853706/gltest.zip)
Please launch mc with this mod installed and upload the crash report.

**Comment by quentin452** [comment]
ok i will try later

**Comment by Meldexun** [comment]
no

**Comment by quentin452** [comment]
[latest.log](https://github.com/Meldexun/Nothirium/files/8853853/latest.log)
without the mod list with multimc launcher

**Comment by quentin452** [comment]
OpenGl Extensions View 6.3.7.0 , say my graphic card ic compatible with 4.6
