### ISSUE TITLE
[1.12.2] Chunk rendering issues & No lightning.

### ISSUE THREAD

**Issue by Z-Tunic** [Meldexun/Nothirium#2]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 6
[___MixinCompat-0.8___]
_MixinBootstrap-1.1.0
astralsorcery-1.12.2-1.10.27
Baubles-1.12-1.5.2
Nothirium-1.12.2-0.1.0-beta
RenderLib-1.12.2-1.0.5

Log:
[latest.log](https://github.com/Meldexun/Nothirium/files/8750390/latest.log)

Debug:
[debug.log](https://github.com/Meldexun/Nothirium/files/8750391/debug.log)

-----

![2022-05-22 17-19-14](https://user-images.githubusercontent.com/36653806/169718834-c9b8d855-5c2f-4c99-a093-4e7e5b107d58.gif)
There are visual errors with Nothirium and it worsens if you have Astral Sorcery installed. The above gif was taken with the installed mods above.

![2022-05-22 17-30-50](https://user-images.githubusercontent.com/36653806/169718858-35746575-4564-4e5c-8ccf-e951870c4978.gif)
This gif was taken without any of the above mods installed. Tthere aren't any visual errors not to mention that the caves & such have darkness.

Note that even if Baubles & Astral Sorcery isn't installed... you can still get some of the rendering issues though it looks to be only in caves but you still get the missing lighting issue. In both gifs I was using Spectator Mode to get a better view. The log & debug files are with the above mods being installed.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.1.1-beta
