### ISSUE TITLE
Mods seems to have many bugs

### ISSUE THREAD

**Issue by 623667595** [Meldexun/Nothirium#21]
All new versions

I am very grateful to the author for developing this mod, which obviously improves FPS. It is one of the few optimized MODS in 1.12.2. I hope the author can make this mod perfect in my lifetime.

Bug: do not turn on the parallel illumination model to blacken.

Some rendering bugs are as follows:
![7V%7G2YQ2Y ST0A M{ OFJ](https://user-images.githubusercontent.com/88877796/174087770-0671110b-1355-4954-ba21-057545ebc17b.png)
![FO652DOGICEP)E~AGJM 4W9](https://user-images.githubusercontent.com/88877796/174087803-e163c6d4-cc7f-4892-9fc7-39a9e8cbd4e4.png)
![IWC`B} XXDLG(S3@8~XRH2](https://user-images.githubusercontent.com/88877796/174087832-1fa8bbbf-f137-414e-bcac-47d83cc0d19a.png)
装有  loliasm-5.3  Sledgehammer  phosphor等优化mod
amd 8300 nvidia516.40驱动版本 1060显卡

**Comment by Meldexun** [comment]
Please use the issue template and provide all the requested information. Also explain the problem properly.

**Comment by 623667595** [comment]
> 请使用问题模板并提供所有要求的信息。还要正确解释问题。

This is not the case when I drag a picture from a random angle. I restart the game and increase the rendering distance.

**Comment by 623667595** [comment]
This happens when I drag from a random angle. When I restart the game and increase the rendering distance, this will not happen.



> 请使用模板并提供所有要求的问题信息。正确解释问题。

This happens when I drag from a random angle. When I restart the game and increase the rendering distance, this will not happen.

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/174118293-b7fb9ff3-3575-4684-89cc-2dd0cf79c0b0.png)
I'm using modularwarfare. The smoke bomb in MODS will show this

**Comment by Meldexun** [comment]
Please create an individual issue for each problem you are experiencing. When you do that be sure to use the issue template and reproduce the issue with as few other mods installed as possible. Also explain what the issue is and how it normally should look like.
