### ISSUE TITLE
Fix vanila bug smooth light

### ISSUE THREAD

**Issue by MiFliK** [Meldexun/Nothirium#22]
![image](https://user-images.githubusercontent.com/80956290/174567017-d691883d-d96f-4235-bfb9-64afd87b64f8.png)
![image](https://user-images.githubusercontent.com/80956290/174567338-05491507-585c-4449-a997-45b0d01e3592.png)

Fix light
![image](https://user-images.githubusercontent.com/80956290/174567365-954e3761-17ff-416e-a6c6-2fdd22039dc3.png)

**Comment by Meldexun** [comment]
Sure don't even try to explain the problem...
