### ISSUE TITLE
crash after world loading

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/Nothirium#28]
**Describe the bug**
When the world loading finished, it suddenly crashed

**To Reproduce**
create the world type RTG (realistic terrain generation)
and after the world loading, crash happens

**Versions**
Nothirium: 0.1.6 - beta
RenderLib: 1.1.0
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Hardware**
CPU:  AMD Ryzen 5 4600H with Radeon Graphics 3.00 GHz
RAM:  DDR4 16GB
GPU:  NVIDIA GeForce GTX 1650 Ti
VRAM:  

**Log File**

[crash report](https://gist.github.com/rebarakuk/8b1d20a86ecabc009c6a91fff4b9e3a6)

[latest log](https://gist.github.com/rebarakuk/d6838cdb1184c00c20e2c7630954d9bb)

**Comment by wed15** [comment]
Chunk Animator might be the one causing the crash. I also got same crash after updating Nothirium to 0.1.6-beta. Probably chunk animator compatibility is broken in some way currently, or having conflict with other mods.

**Comment by Meldexun** [comment]
Nothirium is only compatible with ChunkAnimator-1.12.2-1.2.1

**Comment by wed15** [comment]
Just tried Chunk Animator 1.2.1, but I'm still getting crash even with this version seems cause by different error. 
Here's my crash report generated with Nothirium(+dependencies) and Chunk Animator 1.2.1:
[crash report](https://gist.github.com/wed15/5dc67b8c54ca97782f48d0c055be62a0)
[debug.log](https://gist.github.com/wed15/8d880e426b499b61987cb382017ab6c3)

**Comment by quentin452** [comment]
*Nothirium is not compatible with ChunkAnimator-1.12.2-1.2.1*

**Comment by quentin452** [comment]
I was wrong with the cubicchunk mod
