### ISSUE TITLE
crash with chunk animator 1.2.1

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/Nothirium#29]
**Describe the bug**
After world loading, sky blue color fills the screen and some seconds later, crash happens

Also, without chunk animator, crash doesn't happen

**To Reproduce**
1. create a world
2. crash happens

**Versions**
Nothirium: 0.1.6-beta
RenderLib: 1.1.0
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
Chunk animator: 1.2.1

**Hardware**
CPU:  AMD Ryzen 5 4600H with Radeon Graphics 3.00 GHz
RAM:  DDR4 16GB
GPU:  NVIDIA GeForce GTX 1650 Ti
VRAM: 

**Log File**

[crash report](https://gist.github.com/rebarakuk/7dfe854d39ed0dc95312643933f5ca8d)

[latest log](https://gist.github.com/rebarakuk/2b21c838c795aee4cee0fe787ebcc5e5)

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.1.7-beta
