### ISSUE TITLE
Lighting issues at chunk edges

### ISSUE THREAD

**Issue by embeddedt** [Meldexun/Nothirium#3]
**Describe the bug**

Lighting seems to have issues at chunk boundaries.

**To Reproduce**

1. Create a world (I used seed `-6470902367589166637`).
2. Fly around.
3. Observe strange lighting issues at chunk boundaries (I found one issue at x = 321, z = 210).

**Screenshots/Videos**

![image](https://user-images.githubusercontent.com/42941056/169843557-723756a8-be2d-4ead-9ec8-ace6f3190f1e.png)

**Versions**
Nothirium: 0.1.1
RenderLib: 1.0.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): This is a vanilla instance with Waila installed, but I don't think it's necessary

**Log File**

There are no errors in the log, since this is just a vanilla instance, but I can provide it if necessary.

**Comment by Meldexun** [comment]
Fixed with v1.12.2-0.1.3-beta
