### ISSUE TITLE
crash with somnia

### ISSUE THREAD

**Issue by XiaoAnKing** [Meldexun/Nothirium#30]
[crash-2022-07-09_12.15.23-client.txt](https://github.com/Meldexun/Nothirium/files/9075942/crash-2022-07-09_12.15.23-client.txt)

**Comment by quentin452** [comment]
try to delete chunkanimator ,  phosphor-lighting

**Comment by Meldexun** [comment]
Use the issue template and provide the requested information. Also reproduce the issue with as few mods as possible.
