### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 623667595** [Meldexun/Nothirium#34]
The rendering of NPC and character models in Galaxy mods is wrong, and it is black. Deleting this mods is normal.

**Comment by Meldexun** [comment]
Please use the issue template and provide the requested information.

**Comment by 623667595** [comment]
> Please use the issue template and provide the requested information.
Sorry, I can't understand English. I use translation

**Comment by 623667595** [comment]
Error picture
![2022-07-21_03 34 46](https://user-images.githubusercontent.com/88877796/180066892-f63d9a91-2df8-4cc8-a0b0-554892374b75.png)

**Comment by 623667595** [comment]
![2022-07-21_03 10 23](https://user-images.githubusercontent.com/88877796/180067002-80f66b6c-f90d-41a9-bda2-bcfc5c33d25e.png)
Delete this picture after Mod
