### ISSUE TITLE
The chest and bed not visible

### ISSUE THREAD

**Issue by BellPlayGame** [Meldexun/Nothirium#35]
**Describe the bug**
Chest and bed not visible.

**To Reproduce**
1. Install nothirium mod
2. Start Minecraft
3. Load a world
4. See the chest and bed not visible

**Screenshots/Videos**
https://imgur.com/a/haMNFaw

**Versions**
Nothirium: Nothirium-1.12.2-0.1.7
RenderLib: RenderLib-1.12.2-1.1.1
Forge: 1.12.2-forge-14.23.5.2860
Minecraft: 1.12.2

Other mods (necessary to reproduce the bug): 
obfuscate-0.2.6-1.12.2 (1).jar"
OptiFine_1.12.2_HD_U_G5 (1).jar"
OreExcavation-1.4.143.jar"
OreLib-1.12.2-3.5.2.2 (1).jar"
particleculling-1.12.2-v1.3.1.jar"
Patchouli-1.0-23.6 (1).jar"
performant-1.11.jar"
phosphor-forge-mc1.12.2-0.2.7-universal.jar"
prefab-1.3.0.26 (1).jar"
ProjectE-1.12.2-PE1.4.1.jar"
Quark-r1.6-179 (1).jar"
Rex's-Additional-Structures-1.12.x-(v.2.2.2) (1).jar"
RoguelikeDungeons-1.12.2-1.8.0.jar"
savemystronghold-1.12.2-1.0.0.jar"
SereneSeasons-1.12.2-1.2.16-universal.jar"
StorageDrawers-1.12.2-5.3.8 (1).jar"
Surge-1.12.2-2.0.79.jar"
TConstruct-1.12.2-2.13.0.183 (1).jar"
techguns-1.12.2-2.0.2.0_pre3.1 (1).jar"
TexFix+V-1.12-4.0.jar"
thutcore-1.12.2-5.21.0.jar"
thuttech-1.12.2-6.1.6.jar"
TickDynamic-1.12.2-1.0.3.jar"
tinkersjei-1.0 (1).jar"
TinkerToolLeveling-1.12.2-1.1.0 (1).jar"
TinyMobFarm-1.12.2-1.0.3.jar"
torchmaster_1.12.2-1.8.0.79.jar"
Traverse-1.12.2-1.6.0-69 (1).jar"
twilightforest-1.12.2-3.11.1021-universal-tw.jar"
VanillaFix-1.0.10-150.jar"
vehicle-mod-0.44.1-1.12.2.jar"
WailaHarvestability-mc1.12-1.1.12 (1).jar"
Wawla-1.12.2-2.5.265 (1).jar"
Waystones_1.12.2-4.0.67.jar"
WearableBackpacks-1.12.2-3.1.3.jar"
wings-1.1.6-1.12.2 (1).jar"
WrapUp-1.12-1.1.3 (1).jar"
XL-Food-Mod-1.12.2-1.9.2 (1).jar"
zombieawareness-1.12.1-1.11.16 (1).jar"
[___MixinCompat-0.8___].jar"
AdLods-1.12.2-1.0.8.0-build.0504.jar"
Advanced-Fishing-1.12.2-1.3.3.jar"
aiimprovements-1.12-0.0.1b3.jar"
animania-1.12.2-1.7.3.jar"
AppleCore-mc1.12.2-3.1.4 (1).jar"
AppleSkin-mc1.12-1.0.9 (1).jar"
AttributeFix-1.12.2-1.0.10.jar"
AutoRegLib-1.3-32 (1).jar"
BackTools-1.12.2-7.0.0 (1).jar"
base-1.12.2-3.14.0.jar"
Baubles-1.12-1.5.2 (1).jar"
betteranimals-4.0 (1).jar"
betterbiomeblend-1.12.2-1.1.7-forge.jar"
bettercaves-1.12.2-2.0.3 (1).jar"
BetterFps-1.4.8 (3).jar"
BiblioCraft[v2.4.5][MC1.12.2] (1).jar"
birdsfoods-1.12+-+3.1 (1).jar"
bonsaitrees-1.1.4-b170.jar"
Born+In+A+Barn+V1.8-1.12-1.1.jar"
BuildingGadgets-2.8.4.jar"
carryon-1.12.2-1.12.6.20.jar"
Chameleon-1.12-4.1.3 (1).jar"
ChunkAnimator-1.12.2-1.2.1.jar"
clumps-1.12.2.jar"
CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar"
conarm-1.12.2-1.2.5.4 (1).jar"
Controlling-3.0.10.jar"
CookingForBlockheads_1.12.2-6.4.71 (1).jar"
coroutil-1.12.1-1.2.37 (1).jar"
CosmeticArmorReworked-1.12.2-v4 (1).jar"
CraftStudio-1.0.0.93-mc1.12-alpha.jar"
CreativeCore_v1.9.74_mc1.12.2.jar"
dttraverse-1.5 (1).jar"
DynamicLights-1.12.2.jar"
DynamicSurroundings-1.12.2-3.5.4.3.jar"
DynamicTrees-1.12.2-0.9.5.jar"
ElectroblobsWizardry-4.2.11-MC1.12.2 (1).jar"
ElevatorMod-1.12.2-1.3.14.jar"
EnchantmentDescriptions-1.12.2-1.1.15.jar"
EnderStorage-1.12.2-2.4.6.137-universal (1).jar"
Erebus-1.0.31 (1).jar"
ExCompressum_1.12.2-3.0.26 (1).jar"
exnihilocreatio-1.12.2-0.4 (1).jar"
extrautils2-1.12-1.9.9 (1).jar"
FancyBlockParticles-1.12.x-2.4.1 (1).jar"
FastFurnace-1.12.2-1.3.1.jar"
FastWorkbench-1.12.2-1.7.3.jar"
foamfix-0.10.5-1.12.2.jar"
ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar"
Forgelin-1.8.2 (1).jar"
fossilsarcheology-8.0.4 (1).jar"
FpsReducer-mc1.12.2-1.20.jar"
furniture-6.3.2-1.12.2.jar"
Hwyla-1.8.26-B41_1.12.2 (1).jar"
iChunUtil-1.12.2-7.1.4 (1).jar"
InventoryTweaks-1.63 (1).jar"
IronBackpacks-1.12.2-3.0.8-12 (1).jar"
ironchest-1.12.2-7.0.72.847 (1).jar"
jei_1.12.2-4.15.0.293.jar"
jeiintegration_1.12.2-1.5.1.36 (1).jar"
journeymap-1.12.2-5.7.1-tw (1).jar"
JustEnoughResources-1.12.2-0.9.2.60 (1).jar"
llibrary-1.7.19-1.12.2 (1).jar"
Mantle-1.12-1.3.3.55 (1).jar"
mclib-1.0.2-1.12.2.jar"
metamorph-1.1.7-1.12.2.jar"
MmmMmmMmmMmm-1.12-1.14.jar"
ModernLights-1.0.3_1.12.jar"
MouseTweaks-2.10-mc1.12.2.jar"
mowziesmobs-1.5.4 (1).jar"
Neat+1.4-17.jar"
nofog-1.12.2b3.jar"
NotEnoughItems-1.12.2-2.4.3.245-universal (1).jar"

**Hardware**
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
RAM: 32G
GPU: NVIDIA GeForce GTX 1650
VRAM: 128MB

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:
https://gist.github.com/BellPlayGame/09d9fd087ce71d3e804918ed3d3026ac

**Comment by Meldexun** [comment]
Please reproduce the problem with as few mods as possible.
