### ISSUE TITLE
Bugs from Galacticraft

### ISSUE THREAD

**Issue by Gandalf360one** [Meldexun/Nothirium#37]
**Describe the bug**
1. Entity textures are more dark
When a player travelled to a planned textures from entities will become more darker (also the player texture itself)

**To Reproduce**
1. Install the following mods
2. Create a new World
3. Travel to a planned (moon for example).
5. Look at the player texture or a spawned entity

**Screenshots/Videos**
https://imgur.com/a4iQGfw
https://imgur.com/0WGJx3Q

3. Entities are black (also player, chests, beds etc.)
When a player travelled to a space station every entity will be black.

**To Reproduce**
1. Install the following mods
2. Create a new World
3. Travel to a space station (create on for the earth orbit f.e. and enter it).
5. Look at the player texture, spawned entity, chest, etc.

**Screenshots/Videos**
https://imgur.com/44nQZaH
https://imgur.com/Uaug8mo
https://imgur.com/f9E88T9

**Versions**
Nothirium: 1.12.2-0.1.7
RenderLib: 1.12.2-1.1.1
Forge: 1.12.2- 14.23.2860
Minecraft: 1.12.2
Mixinbooter: 1.12.2-4.2 
Galacticraft: 1.12.2-4.0.2.284

**Hardware**
CPU: Intel i7-7700K
RAM: 32 GB
GPU: Geforce GTX 1070 TI
VRAM: 8

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:
https://gist.github.com/Gandalf360one/2a8bcfaceb7055c7dd56672da93802bb

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.1.8-beta
