### ISSUE TITLE
Update notirium-1.12.2-0.1.8 questions

### ISSUE THREAD

**Issue by 623667595** [Meldexun/Nothirium#38]
1.12.2
I updated notirium, renderlib, entityculling. It is not clear which caused the module rendering to flicker.

**Hardware**
CPU: amd 8300
RAM: 10g
GPU: N 1060 
VRAM: 3g

https://user-images.githubusercontent.com/88877796/182904030-40bf31f8-a4ec-4d91-8e17-a9ed208a8347.mp4

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/182904478-c2d48b75-fb20-4cb7-8058-85ce7d87ffc2.png)
![image](https://user-images.githubusercontent.com/88877796/182905054-ebce3e6c-e607-451e-9f45-008c08d21a22.png)

**Comment by 623667595** [comment]
It has been found that the bug box is the super giant cave producer of magic baby.

**Comment by Meldexun** [comment]
I assume this is fixed/not a problem of Nothirium and thus closed this.
If this is not the case please provide **all** the information requested in the issue template and add a comment mentioning that this is still a problem.
