### ISSUE TITLE
Galaxy Space bug

### ISSUE THREAD

**Issue by Gandalf360one** [Meldexun/Nothirium#39]
**Describe the bug**
Install the following mods and travell to the moon or the space station in the orbit of the earth.
There will be a big white horizontal line.

**To Reproduce**
1. Install the following mods
2. Create a new world
3. Travell with a rocket to the moon or the space station in the orbit of the earth.
4. look at the horizont

**Screenshots/Videos**
https://imgur.com/BkInPcM

**Versions**
Nothirium: 1.12.2-0.1.8-beta
RenderLib: 1.12.2-1.1.2
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
MixinBooter: 4.2
AsmodeusCore: 1.12.2-0.0.31
Galacticraft: 1.12.2-4.0.2.284
GalaxySpace: 1.12.2-2.0.19
Optifine: 1.12.2-G5

**Hardware**
CPU: i7-7700K
RAM: 32GB
GPU: Geforce GTX 1770TI
VRAM: 8GB

**Log File**
https://gist.github.com/Gandalf360one/ae36db1a39b3a31b77f6800ca7d1650c

**Comment by Meldexun** [comment]
I'm unable to reproduce this.

**Comment by Gandalf360one** [comment]
Sorry for the late replay.
I did some research in the mean time (till you responded) and found out that the option "Fast Rendering" from Optifine caused that problem.

**Comment by Gandalf360one** [comment]
Sorry for the late replay.
I did some research in the mean time (till you responded) and found out that the option "Fast Rendering" from Optifine caused that Issue.
