### ISSUE TITLE
Incompatibility with ChunkAnimator

### ISSUE THREAD

**Issue by Mavendow** [Meldexun/Nothirium#42]
**Describe the bug**
Immediate crash upon opening a world when ChunkAnimator is installed.

**Reproducibility**
- [X] I reproduced this issue with as few other mods as possible installed.

**To Reproduce**
1. Install Nothirium
2. Install ChunkAnimator
3. Launch MC
4. Open a world

**Versions**
Nothirium: 0.1.9-beta
RenderLib: 1.1.7
Forge: 14.23.5.2860 
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Chunk Animator 1.2

**Hardware**
CPU: Ryzen 7 2700x
RAM: 32768MB (virtual memory disabled)
GPU: GeForce 1080
VRAM: 8192MB

**Log File**
https://pastebin.com/NvnpiZwG

**Comment by Meldexun** [comment]
Update chunk animator
