### ISSUE TITLE
Remove Gregtech CE: Unofficial from incompatibilities on CF page

### ISSUE THREAD

**Issue by Irgendwer01** [Meldexun/Nothirium#44]
As of version 2.4.2 of GTCEu, Nothirium compatibility has been fixed (https://github.com/GregTechCEu/GregTech/releases/tag/v2.4.2) so it should be removed from Incompatibilities on the CF page.

**Comment by Meldexun** [comment]
I updated the curseforge page. Thank you for informing me.
