### ISSUE TITLE
serious graphical bug with soft lighting (Vanilla bug)

### ISSUE THREAD

**Issue by MiFliK** [Meldexun/Nothirium#45]
smooth light not working properly

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ yes] I reproduced this issue with as few other mods as possible installed.
- [yes] I am unable to reproduce this issue consistently.

**To Reproduce**
2.build a staircase out of white blocks or dig down in the mine in the form of steps
3.Place a torch or any light source
4.or put a block above the water and you will see a black spot instead of smooth lighting

https://imgur.com/a/eK3zdWM)
![image](https://user-images.githubusercontent.com/80956290/199504569-ec608d57-f0ff-4b88-9a26-3bac78b7d8c1.png)
![image](https://user-images.githubusercontent.com/80956290/199505052-8b9d07ac-770e-49d0-ac76-5ad185f47560.png)
![image](https://user-images.githubusercontent.com/80956290/199505693-a817ea4a-3f9c-4956-8ae3-90ce1b74ef0b.png)

**Versions**
0.1.10 beta
1.1.9
14.23.5.2860
1.12.2
Optifine

**Hardware**
intel core i5 7th laptop
8 gb
1050 mobile
VRAM: 

Additional Information
this bug with lighting occurs on all versions of minecraft up to 1 17
The only mods that fix it are triangulator and sodium
This bug greatly spoils the game with shaders and buildings, especially with torches or steps
at the moment it does not fix more than one mod on 1 12 2
I really hope that this bug will be fixed.
As a perfectionist, I don't like it.
it does not depend on the level of soft lighting
information that may help
https://github.com/sp614x/optifine/issues/1287
https://www.reddit.com/r/Minecraft/comments/6us5yd/til_smooth_lighting_looks_a_lot_smoother_in_beta/
https://bugs.mojang.com/browse/MC-43968

**Comment by Meldexun** [comment]
This issue tracker is used exclusively for issues with Nothirium.

Aside from that this feature request is out of scope for Nothirium and won't be added to the mod.
