### ISSUE TITLE
Crash with FarPlaneTwo

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/Nothirium#46]
[debug.log](https://github.com/Meldexun/Nothirium/files/10141861/debug.log)
[latest.log](https://github.com/Meldexun/Nothirium/files/10141863/latest.log)

**Comment by kasia1403-is-a-stupid-retard** [comment]
If you ignore bug report templates, your issues get ignored too dumbass.

**Comment by Meldexun** [comment]
Please follow the issue template.
