### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/Nothirium#5]
[crash-2022-05-24_15.16.40-client.txt](https://github.com/Meldexun/Nothirium/files/8763162/crash-2022-05-24_15.16.40-client.txt)

**Comment by embeddedt** [comment]
This looks like a mixin conflict, please send your `latest.log` again.

**Comment by Kasia1403** [comment]
[latest.log](https://github.com/Meldexun/Nothirium/files/8763672/latest.log)

**Comment by Kasia1403** [comment]
Is this mod also still incompatible with Chunk Animator ?

**Comment by Kasia1403** [comment]
I think it is working ( Nothirium with Chunk Animator ). But not with FarPlaneTwo.

**Comment by Meldexun** [comment]
The original issue (dependencies not being installed) has been resolved. Thus I will close this now.
For all other bugs please create a new issue.
