### ISSUE TITLE
0.2.0 - beta just doesn't start

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/Nothirium#53]
**Describe the bug**
crash happens when forge mod loading

**Reproducibility**
- [ x ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
only with nothirium, renderlib, mixin bootstrap, minecraft crashes.

**Versions**
Nothirium: 0.2.0 - beta
RenderLib: 1.1.10
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
mixinbootstrap 1.1.0

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 

**Log File**
[crash report](https://gist.github.com/rebarakuk/0fc86abf8bda41b9d98cd7be2cff37bd)

[latest log](https://gist.github.com/rebarakuk/dd39c454a6798354dc1a41b7564da25e)

**Comment by hampop** [comment]
you are using a outdated version of RenderLib you need 1.2.5 
https://github.com/Meldexun/RenderLib/releases/tag/v1.12.2-1.2.5
