### ISSUE TITLE
Incompatibility with Better Biome Blend

### ISSUE THREAD

**Issue by 1950694292** [Meldexun/Nothirium#55]
**Describe the bug**
biome color dosent render properly，works fine on previous version

**Reproducibility**

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. See error

**Screenshots/Videos**
![without the mod](https://user-images.githubusercontent.com/126590119/221903660-838a9497-14c9-4a01-9a7f-58b414c197a9.png)without the mod
![with the mod](https://user-images.githubusercontent.com/126590119/221903670-7757ee1f-7fd2-4f69-a364-fc9edf9378ee.png)
with the mod
**Versions**
Nothirium: Nothirium-1.12.2-0.2.0-beta
RenderLib: RenderLib-1.12.2-1.2.5
Forge: 2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): betterbiomeblend-1.12.2-1.1.7

**Hardware**
CPU: i3-9100f
RAM: /
GPU: gtx 1650
VRAM: /

**Log File**
/

**Comment by Meldexun** [comment]
Should be fixed in 1.12.2-0.2.1-beta
