### ISSUE TITLE
crash with codechickenlib

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/Nothirium#56]
**Describe the bug**
crash when mod loading

**Reproducibility**
- [ x ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
start minecraft

**Versions**
Nothirium: 0.2.0 - beta
RenderLib: 1.2.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
codechickenlib 3.2.3.358

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 

**Log File**
[crash report](https://gist.github.com/rebarakuk/1aa4049a51fb2e745df7482f7e2e5a9b)

[latest log](https://gist.github.com/rebarakuk/08eedefb4c484bccdba951a6756435c6)

**Comment by quentin452** [comment]
i have the same crash

**Comment by Gandalf360one** [comment]
Same Problem here.

**Comment by Meldexun** [comment]
Should be fixed in 1.12.2-0.2.1-beta
