### ISSUE TITLE
Crash with some Immersive Engineering Structures

### ISSUE THREAD

**Issue by Gandalf360one** [Meldexun/Nothirium#57]
**Describe the bug**
When creating certain Multiblock-Structures from Immersive Engineering and also addons the game will crash while setting it up (placing the blocks for the structure and sneak right clicking it with a hammer at the main block)

Some structures that crash the game (their are more):
- Metall Press
- Crusher
- Steam Turbine
- Gas Turbine

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Create a new World
2. Build one Structure (the projector can be used for it to save time) from the list above
3. Try to activate it (hammer)

**Screenshots/Videos**
https://imgur.com/a/nJMH96n

**Versions**
Nothirium: 1.12.2-0.2.1-beta
RenderLib: 1.12.2-1.2.6
Forge: 1.12.2-14.23.5.2860
Minecraft: 1.12.2
Mixin: !mixinbooter-7.0
Immersive Engineering: 0.12-98
immersivepetroleum: 1.12.2-1.1.10
Immersive Technology: 1.12.2-1.8.94

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 

**Log File**
https://pastebin.com/UU3YGyuP

**Crash File**
https://pastebin.com/ZgcYNZUe

**Comment by Meldexun** [comment]
This issue is caused by ImmersiveEngineering/ImmersivePetroleum/ImmersiveTechnology using the wrong method to set the color when rendering their stuff.
I added a workaround to Nothirium to not crash the game but this can still cause graphical issues (which can also happen without Nothirium being installed).

**Comment by Gandalf360one** [comment]
Thx for closing it (forgot it).
The latest update fixed that issue (big thank you!)
