### ISSUE TITLE
Crashes with Advanced Rocketry

### ISSUE THREAD

**Issue by TheAirBlow** [Meldexun/Nothirium#58]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Make a space station
2. Jump down
3. Crash

**Versions**
Nothirium: 0.2.1-beta
RenderLib: 1.2.6
Forge: 14.23.5.2860
Minecraft: 1.12.2
AdvRocketry: 1.7.0-232

**Hardware**
CPU: AMD Ryzen 5 3550H
RAM: 8 GB DDR4
GPU: AMD Radeon RX 560X
VRAM: 4 GB GDDR5

**Log File**
https://mclo.gs/doL8Dwq

**Comment by dazadazu** [comment]
So to be clear you aren't crash landing into a planet? ... haha jk but I do hope this gets resolved.

**Comment by TheAirBlow** [comment]
> Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.

Me: **m a k e. a. s p a c e. s t a t i o n.**

**Comment by Meldexun** [comment]
This issue is caused by AdvancedRocketry using the wrong method to set the color when rendering their stuff.
I added a workaround to Nothirium to not crash the game but this can still cause graphical issues (which can also happen without Nothirium being installed).

**Comment by TheAirBlow** [comment]
> This issue is caused by AdvancedRocketry using the wrong method to set the color when rendering their stuff. I added a workaround to Nothirium to not crash the game but this can still cause graphical issues (which can also happen without Nothirium being installed).

Can you tell me which one exactly? If I won't be lazy, I could make a fork of advanced rocketry fixing at least two bugs which happened to me multiple times, not including this one.

**Comment by TheAirBlow** [comment]
P.S. I'm unbelievably stupid! It's literally what the crashlog says. Also, why did you go on to optimise BufferBuilder without even making a proper implementation?
