### ISSUE TITLE
Crash when right clicking grill from primal_tech

### ISSUE THREAD

**Issue by theamazingjz** [Meldexun/Nothirium#59]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
I was playing the modpack "sevtech ages" and when I placed an item on the grill it just crashed the entire game. I then made a test world only using Primal Tech along with Nothirium with its dependencies and the same issue happened.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Install Nothirium, RenderLib, Primal Tech and MixinBootstrap
2. Make a world and place down a grill
3. Place an item in it to crash the game

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
Nothirium: 0.2.1 beta 
RenderLib: 1.2.6
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
Primal Tech 0.3.5

**Hardware**
CPU: Intel i9 12900h
RAM: 32gb DDR5 
GPU: Nvidia RTX 3080 ti laptop
VRAM: 16gb

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
debug.log: https://gist.github.com/theamazingjz/6eecb01066b96e3d74faf5be93110ce0
crash report: https://gist.github.com/theamazingjz/b1e1acc2c94e99291cc655293e0e69a9

**Comment by Meldexun** [comment]
This issue is caused by PrimalTech using the wrong method to set the color when rendering their stuff.
I added a workaround to Nothirium to not crash the game but this can still cause graphical issues (which can also happen without Nothirium being installed).
