### ISSUE TITLE
Nothirium Prevents Optifine from Disabling Fog (Minor Bug)

### ISSUE THREAD

**Issue by nerdula** [Meldexun/Nothirium#6]
**Describe the bug**
Having Nothirium installed causes this minor bug in Optifine that forces the game to be run on "Fancy Fog." Setting to Fast specifically on the Fog option in Optifine loads the fog as expected for normal Optifine but with the setting set to Off, fog loads with the fancy specifications. Optifine only issue as using the NoFog mod on Curse does not seem to have the same issue. Hopefully didn't miss anything that could be a variable in the issue except maybe the resource packs I used.

**To Reproduce**
1. Have Nothirium and dependencies installed with Optifine (Versions specified below)
2. Load the game and go to Video Settings -> Details -> Fog: OFF
3. Create a world and load into it
4. You will find that the fog is still there despite the option being on OFF

**Screenshots/Videos**
(https://user-images.githubusercontent.com/87387990/170418360-24f6a64b-6bba-442c-a624-61ba84430493.png)

**Versions**
Nothirium: Nothirium-1.12.2-0.1.1-beta.jar (Latest off Curse)
RenderLib: RenderLib-1.12.2-1.0.5.jar
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Mod that adds Mixins (In my case I used !mixinbooter-4.2.jar), Optifine 1.12 (preview_OptiFine_1.12.2_HD_U_G6_pre1.jar)

**Hardware**
CPU: Intel Core i7-9700 @3.00 GHz
RAM: 16GB of 8x2 DDR4 @2666 MHz
GPU: Nvidia GeForce GTX 1660Ti
VRAM: 6GB

**Log File**
https://paste.ee/p/mFVgb

**Comment by Irgendwer01** [comment]
@nerdula Have u tried if u can disable fog with an other mod like BetterFPS?

**Comment by nerdula** [comment]
> @nerdula Have u tried if u can disable fog with an other mod like BetterFPS?

As said above, seems to be an Optifine only issue, mods such as NoFog work fine. Never knew betterFPS even had a remove fog option, I thought it was always either fast or fancy from what I remember.

**Comment by Meldexun** [comment]
Optifine fog settings work correctly as of v1.12.2-0.1.4-beta
