### ISSUE TITLE
Astral Sorcery's Celestial Gateway has broken textures, rendering it barely usable

### ISSUE THREAD

**Issue by SilverBeamx** [Meldexun/Nothirium#69]
**Describe the bug**
The Celestial Gateway from Astral Sorcery exhibits broken twitching textures. This is especially bad "aiming" at a star is required in order to initiate teleportation

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Step on any Celestial Gateway from Astral Sorcery. A "dome-shaped" texture should fade-in around the player. Instead, the texture glitches, spazzing out even when not moving the camera around.

**Screenshots/Videos**
Screenshot of the issue:
![NothCelestial](https://github.com/Meldexun/Nothirium/assets/44263986/3d76537f-cf1c-44eb-9fd1-97e0539c58c6)

Video of the issue:
https://imgur.com/ufhp5Vs

**Versions**
Nothirium: 0.2.4-beta
RenderLib: 1.2.8
Forge: 14.23.5.2862
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Astral Sorcery 1.10.19

**Hardware**
CPU: Intel i5-8600k
RAM: 7200Mb allocated to Minecraft
GPU: GTX 1060
VRAM: 6Gb

**Log File**
https://gist.github.com/SilverBeamx/40ce85c207df9157821b198e3f3423dd

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.3.1-beta
