### ISSUE TITLE
Chunk not compiling when leaving world while a lot of chunks are compiling

### ISSUE THREAD

**Issue by Dan4oby** [Meldexun/Nothirium#70]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Textures sometimes becomes invisible when i join the world.
I experienced this issue also with only perfomance mods installed but i didnt know which mod cause this issue. Mods that were installed:
BetterFps-1.4.8
censoredasm5.13
EntityCulling-1.12.2-6.3.1
foamfix-0.10.15-1.12.2
FpsReducer-mc1.12.2-1.20
FullscreenWindowed-1.12-1.6.0-1
modernsplash-1.12.2-1.2.2.2
Nothirium-1.12.2-0.2.4-beta
OptiFine_1.12.2_HD_U_G5_MOD
particleculling-1.12.2-v1.4.1
phosphor-1.12.2-0.2.9.2-SNAPSHOT-universal
randompatches-1.12.2-1.22.1.10
RenderLib-1.12.2-1.2.8
scalingguis-1.12.2-1.0.3.0
SmoothFont-mc1.12.2-2.1.4
UniversalTweaks-1.12.2-1.6.0
vintagefix-0.2.1

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**Screenshots/Videos**
(https://imgur.com/a/krifoMm)

**Versions**
Nothirium: 
RenderLib: latest
Forge: latest
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Hardware**
CPU: 2700x
RAM: 16GB
GPU: GT1030
VRAM: 2GB

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.3.1-beta
