### ISSUE TITLE
Malisis Doors Hi-tech Door Issue

### ISSUE THREAD

**Issue by Elephant1214** [Meldexun/Nothirium#71]
**Describe the bug**
The Hi-Tech door from Malsis Doors renders with no texture. Sometimes it will start with its texture, but then it will eventually lose it and turn pink and black. Sometimes random blocks from around it will appear in the door and random blocks around the door will disappear. I have also had them clip through the ground multiple times and render 50+ blocks away from where they actually are.

**Reproducibility**
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Place a Hi-tech Door
2. If it looks normal, open and close it quickly

**Screenshots/Videos**
![2023-07-03_11 05 02](https://github.com/Meldexun/Nothirium/assets/46881115/6331e58f-f9f4-4d9b-80c5-ae2b1e494863)
![2023-07-03_11 10 03](https://github.com/Meldexun/Nothirium/assets/46881115/069e3318-05dc-4ef5-b23f-4fba155a8abe)
![2023-07-03_11 21 52](https://github.com/Meldexun/Nothirium/assets/46881115/47a6ea92-faee-4011-9f50-d2f525dd57f9)
![2023-07-03_11 34 10](https://github.com/Meldexun/Nothirium/assets/46881115/9543910e-cfd6-4372-9e4a-63657e232fb4)

These two screenshots were taken within a few seconds of each other, the first one was taken when I first logged into the server.
![2023-07-03_11 25 30](https://github.com/Meldexun/Nothirium/assets/46881115/16016440-f522-4394-b0a3-ca7faeb79ef7)
![2023-07-03_11 25 40](https://github.com/Meldexun/Nothirium/assets/46881115/6b85aa52-994f-4f4d-94a4-b66eabc2979b)

**Versions**
Nothirium: 0.2.4-beta
RenderLib: 1.2.8
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
MalisisCore: 1.12.2-6.5.1-SNAPSHOT
MalisisDoors: 1.12.2-7.3.0
OptiFine: HD U G5

**Hardware**
CPU: Ryzen 7 2700X
RAM: 32GB CL16 at 3000MHz
GPU: RTX 2070 SUPER
VRAM: 8GB

**Log File**
https://paste.md-5.net/ekelusapoj.md

**Comment by Meldexun** [comment]
This isn't a Nothirium issue. But Malisis Doors (most likely) won't receive another update. So I fixed it in v1.12.2-0.3.3-beta.
