### ISSUE TITLE
Some 'Tesselating block model' crash.

### ISSUE THREAD

**Issue by MagmaBro123** [Meldexun/Nothirium#76]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Title.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Use the mod and fly around. The game will crash randomly.

**Screenshots/Videos**
N/A.

**Versions**
See #75 for mod info. This happened shortly after opening that.

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 
**No idea how to get this info.**

**Log File**
[crash-2023-07-22_11.28.31-client.txt](https://github.com/Meldexun/Nothirium/files/12136931/crash-2023-07-22_11.28.31-client.txt)

**Comment by Meldexun** [comment]
This is a subaquatic issue.
