### ISSUE TITLE
when i uncap my frames  with GL4.3 and GL4.2 strange things happens 

### ISSUE THREAD

**Issue by Floi1** [Meldexun/Nothirium#77]
**Describe the bug**
when you uncap your frames odd stuff happens when moving 

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**

1. Go to 'go ingame and uncap your frames  with GL4.3 or GL4.2'
2. Click on 'then you will see the bug when moving'

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

https://github.com/Meldexun/Nothirium/assets/91851019/8a31a17b-3c6b-49a4-8750-eb5177579759

https://github.com/Meldexun/Nothirium/assets/91851019/e8f8a4d4-215d-4e40-a2d0-c993e86d012e

**Versions**
Nothirium: 0.3.2
RenderLib: 1.3.1
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
MixinBootstrap

**Hardware**
CPU:  AMD amd ryzen 5 5500u
RAM: 8GB
GPU: Igpu vega 7
VRAM: idk

**Log File**

**Comment by Floi1** [comment]
i just updated my amd driver to 23.7.2 it seems to fix the issue for me so this is a amd driver issue. In the video i was using  amd driver  23.7.1 

https://github.com/Meldexun/Nothirium/assets/91851019/c2f6fca5-b9d7-4450-991c-043691fa1c18

**Comment by Meldexun** [comment]
Good to know. I will close this now.
