### ISSUE TITLE
IE Distillation tower rendering bug

### ISSUE THREAD

**Issue by Srdjan-V** [Meldexun/Nothirium#8]
**Describe the bug**
After loading the world the tower looked like this
![2022-05-26_17 05 10](https://user-images.githubusercontent.com/78452357/170519412-a65d1304-d484-4e41-87c8-1ab89ab25e3b.png)

So i thought that rebuilding it would fix it, but it crashed the JVM. This seems to happen every time you try to build it.

**Versions**
Nothirium: 0.1.1-beta
Entity Culling: 6.0.1-beta
RenderLib: 1.0.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):IE

**Hardware**
CPU: Ryzen 3600
RAM: 16G 6 allocated
GPU: gtx 1660 S
VRAM: 6G

**Log**
https://paste.ee/p/8EaCc

**Comment by Meldexun** [comment]
Should be fixed with v1.12.2-0.1.3-beta

**Comment by Srdjan-V** [comment]
I made a clean environment with the only necessary mods just to make sure that no other incompatibility's ware present, and it is still rendering incorrectly
![2022-05-26_21 06 03](https://user-images.githubusercontent.com/78452357/170559951-4001023a-04cc-4fcd-af2b-b6364488b619.png)


**mods used**
  [✔️] _MixinBootstrap-1.1.0
  [✔️] EntityCulling-1.12.2-6.0.2
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.10
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] MCTImmersiveTechnology-1.12.2-1.9.100
  [✔️] Nothirium-1.12.2-0.1.3-beta
  [✔️] RenderLib-1.12.2-1.0.6

**Comment by Meldexun** [comment]
Now I understand what you mean. Please explain it in more detail next time as I don't know every mod and how things are supposed to look. Also you could have reopened the issue since it wasn't fixed.

Anyway v1.12.2-0.1.4-beta has a workaround for Immersive Petroleum

**Comment by Srdjan-V** [comment]
>Please explain it in more detail next time as I don't know every mod 

Sorry about that, I will try to explain ti better in the future.

>Also you could have reopened the issue since it wasn't fixed.

Are you sure im able to do that, I don't think i can reopen a issue if a contributor/owner closed it.

**Comment by Meldexun** [comment]
> Are you sure im able to do that, I don't think i can reopen a issue if a contributor/owner closed it.

I check and I think you are right that you can't reopen the issue in this case.

**Comment by Srdjan-V** [comment]
So in the future do you want me to open a new issue or comment on the existing?
