### ISSUE TITLE
REALLY Hoping for it coming in update

### ISSUE THREAD

**Issue by ralseilii** [Meldexun/Nothirium#85]
Will the mod compatible with onDemandAnimatedTexture of censormedasm later? The onDemandAnimatedTexture feature of censormedasm actually boosts fps 3 times and nothirium helps fps become stable and high. I really really hope the feature of censormedasm can be used with nothirium together. In that way it will be the best fps boosting mod in 1.12.2 modpack and the mod will reach higher .

**Comment by Meldexun** [comment]
Compatibility will be added eventually.
Please keep question/request away from the issue tracker in the future.
