### ISSUE TITLE
Incompability with Moving Elevators (1.12.2)

### ISSUE THREAD

**Issue by WaterOtter86** [Meldexun/Nothirium#91]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Using Nothirium and Moving Elevators makes Elevators invisible

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ X] I reproduced this issue with as few other mods as possible installed.(log shown here also has few more mods but i did test it with Nothirium and ME only)
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1.Install Nothirium and Moving Elevator(as few other mods as possible)
2.Build said elevator ingame
3.Try to make it move
4.Look as your character moves thru space without any visible flooring under em.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_242](https://github.com/Meldexun/Nothirium/assets/50717708/bcf6457a-9b2a-4d1a-804d-0453280262a9)

**Versions**
Nothirium: 0.3.4 - beta
RenderLib:  1.3.3
Forge: 2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Moving Elevators

**Hardware**
CPU: I5 - 9600K
RAM:  32 GB
GPU:  GTX 1660 S
VRAM:  6 GB

**Log File**
https://mclo.gs/FOntioX

**Comment by Meldexun** [comment]
Looking at this now. MovingElevators added a fix for this incompatibility in MovingElevators 1.4.6.
