### ISSUE TITLE
nothirium incompatible with vintagium

### ISSUE THREAD

**Issue by BloxMaster3** [Meldexun/Nothirium#92]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
crashes when loading both nothirium and vintagium installed

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Go to https://github.com/Asek3/sodium-1.12/actions/runs/8217114565 and download vintagium and extract and put the regular version of vintagium (not dev) into mods folder
2. Go to https://github.com/CleanroomMC/Cleanroom/actions/runs/8229431020 and download installer extract then double click on installer and install client into .minecraft folder (vintagium dependency)
3. run minecraft with nothirium also installed
4. Should crash

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
Nothirium: Nothirium-1.12.2-0.3.4-beta
RenderLib: RenderLib-1.12.2-1.3.4
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): vintagium and cleanroom (vintagium dependency)

**Hardware**
CPU: i9-10900x
RAM: 18432MB
GPU: NVidia RTX 2070 Ventus
VRAM: 8GB

**Log File**
https://gist.github.com/BloxMaster3/b201517ba051cece8de244d7d9984d46

**Comment by Meldexun** [comment]
This is not an incompatibility/issue. Vintagium and Nothirium both replace the chunk rendering engine of Minecraft which means you have to decide which you want to use.

**Comment by BloxMaster3** [comment]
> This is not an incompatibility/issue. Vintagium and Nothirium both replace the chunk rendering engine of Minecraft which means you have to decide which you want to use.

would you mind adding it to the CurseForge list of incompatibilities though?
