### ISSUE TITLE
[Feature Request] Edge chunk culling

### ISSUE THREAD

**Issue by HowardZHY** [Meldexun/Nothirium#97]
Something like
https://github.com/FalsePattern/NeodymiumUnofficial/blob/8598f6c1a86bb2bd057c02c3a9c2f9cb52930bc1/src/main/java/makamys/neodymium/renderer/NeoRenderer.java#L261 or https://github.com/someaddons/betterfpsdistances

**Comment by HowardZHY** [comment]
> That's already part of the mod.

Where? or this won't work if fog was disabled by OptiFine?

**Comment by Meldexun** [comment]
If there is no fog then there is nothing to cull. So, yes if you disable the fog then nothing will be culled.

**Comment by HowardZHY** [comment]
> If there is no fog then there is nothing to cull. So, yes if you disable the fog then nothing will be culled.

Can you add an option to cull even there's no fog? to get even higher fps

**Comment by Meldexun** [comment]
Actually I was wrong. The fog culling is always active. Also, when fog is disabled in optifine.

**Comment by HowardZHY** [comment]
> Actually I was wrong. The fog culling is always active. Also, when fog is disabled in optifine.

Just found a Tweakroo fog option breaks it, thank you for your reply anyway

**Comment by HowardZHY** [comment]
Seems this breaks again with latest, not sure since which build

> Actually I was wrong. The fog culling is always active. Also, when fog is disabled in optifine.

**Comment by HowardZHY** [comment]
Also, I wonder if there's a config option that could make it more aggresive
